Sprint 8 solution time and duration
PaperAlex/java-kanban pull request #3
Opened 2024-07-20 16:19 UTC by PaperAlex

2024-07-21 03:30 UTC, EugeneLenkevich requested changes
Привет, Alex! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2024-07-21 03:30 UTC, EugeneLenkevich commented on src/exceptions/ManagerTimeException.java
> +public class ManagerTimeException extends RuntimeException {
Как то слишком ли сурово кидать непроверяемое исключение из-за того что задачи пересекаются :)
RuntimeException - это поломка, непредвиденная ошибка, а пересечение задач вполне себе штатная ситуация и ее можно и нужно обработать 
Лучше все таки тут подойдет проверяемое исключение
extends Exception

2024-07-21 03:30 UTC, EugeneLenkevich commented on src/model/Epic.java
> +            return "null";
Может лучше пустую строку чем строку "null", это может показаться неочевидным если думать в терминах бизнес задачи, там ведь или есть время или его нет, а тут еще одна неожиданная строка больше похожая на детали реализации, это же потом где то может выводиться пользователю :)

2024-07-21 15:03 UTC, PaperAlex commented on src/exceptions/ManagerTimeException.java
> +public class ManagerTimeException extends RuntimeException {
Спасибо. Поправил.

2024-07-21 18:21 UTC, EugeneLenkevich requested changes
Привет, там вроде еще несколько мест осталось с "null", посмотри, пожалуйста

![image](https://github.com/user-attachments/assets/14cc8ae2-27b8-4572-ab1a-05113dcaf8e6)

2024-07-22 08:53 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-07-30 18:48 UTC, merged