Sprint 9 solution http api
PaperAlex/java-kanban pull request #4
Opened 2024-08-02 17:43 UTC by PaperAlex

2024-08-02 18:13 UTC, EugeneLenkevich requested changes
Привет, Алексей! Спасибо за ПР

Это, конечно, муторное дело разбирать вручную запросы, но потом это будет проще, современные фреймворки делают это гораздо проще :)

От очень хочется поработать с тестами, отметил несколько моментов, посмотри комментарии, пожалуйста :)

2024-08-02 18:13 UTC, EugeneLenkevich commented on test/managertest/HttpTaskServerTest.java
> +    Gson gson = new GsonBuilder()
А давай все таки создание gson вынесем в отдельный метод, например, в отдельном классе чтобы у нас была только одна точка создания и настройки объекта-сериализатора, иначе будет трудновато потом такой код менять, можно что то пропустить :)

2024-08-02 18:13 UTC, EugeneLenkevich commented on test/managertest/HttpTaskServerTest.java
> +    public HttpTaskServerTest() throws IOException {
Конструктор в тесте не нужен, кстати

2024-08-02 18:13 UTC, EugeneLenkevich commented on test/managertest/HttpTaskServerTest.java
> +        HttpRequest request = HttpRequest.newBuilder()
```
        HttpRequest request = HttpRequest.newBuilder()
                .uri(url)
                .GET()
                .build();
```

Тест - по сути описание некоего бизнес-сценария, своеобразная документация по тому как наша логика должна работать, а вот технический код несколько затрудняет чтение этой логики, давай попробуем вынести весь этот код создания запросов в отдельные вспомогательные методы и посмотрим как наш код будет после этого выглядеть :)

2024-08-03 09:30 UTC, PaperAlex commented on test/managertest/HttpTaskServerTest.java
> +    public HttpTaskServerTest() throws IOException {
Легкая паника, когда без конструктора все перестало работать.

2024-08-03 18:06 UTC, EugeneLenkevich commented on test/managertest/HttpTaskServerTest.java
> +    public HttpTaskServerTest() throws IOException {
Но сейчас же вроде нормально работает :)

2024-08-03 18:06 UTC, EugeneLenkevich approved these changes
Да, примерно так, спасибо :)

2024-08-13 15:51 UTC, merged